# Generated by Django 5.2.7 on 2025-10-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='matricule',
            field=models.CharField(default=None, max_length=100, unique=True, verbose_name='Matricule'),
        ),
    ]
