# Generated by Django 5.2.7 on 2025-12-13 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employe_matricule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=100, unique=True, verbose_name='Nom du service')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'service',
                'ordering': ['nom_service'],
            },
        ),
        migrations.RemoveField(
            model_name='employe',
            name='id_departement',
        ),
        migrations.AlterField(
            model_name='employe',
            name='matricule',
            field=models.CharField(max_length=100, unique=True, verbose_name='Matricule'),
        ),
        migrations.AddField(
            model_name='employe',
            name='service',
            field=models.ForeignKey(db_column='id_service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='employees.service'),
        ),
        migrations.DeleteModel(
            name='Departement',
        ),
    ]
